### ISSUE TITLE
Killing xrmd process and creating second encoder session breakes the first one.

### ISSUE THREAD

**Issue by ev-zhuravlev** [Xilinx/XRM#4]
Hello, 
I have encountered the following problem:

1. Create first encoder session
2. kill xrmd process: kill -9 <xrmd PID>
3. Create second encoder session

Until step 3 first session continue to work. After that xma_enc_session_send_frame in the first session starts to fail with the following error messages:

xma-vcu-encoder Error: (get_raw_host_frame) Buffer Pool full - no free buffer available
xma-vcu-encoder xma_encoder_send_frame: ERROR: host buffer write failed

There is no such problem if no xrmd killing is performed. Two session and running without error simultaneously.

OS info:
lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	OracleServer
Description:	Oracle Linux Server release 7.9
Release:	7.9
Codename:	n/a

It is Amazon EC2 VT1 instance.

**Comment by bttu** [comment]
@ev-zhuravlev xrmd is running as a resource manager daemon at the backend, This process can NOT be killed during the whole life cycle, otherwise unexpected behavior may happen. It's out of control, I would say. May I know why here step 2 is taken?

**Comment by ev-zhuravlev** [comment]
We have systemd daemons that depend on xrmd so I am testing what happens in the case of the crash in xrmd process.

**Comment by bttu** [comment]
Then it looks like the test case needs to be revised.

**Comment by ev-zhuravlev** [comment]
Do you mean that our test case should be revised?
It is possible to create a situation that no encoder can be created until machine is restarted by killing xrmd.
When this happens creation of encoder failed due to the following crash:

#0  0x00007f372e53a387 in raise () from /lib64/libc.so.6
#1  0x00007f372e53ba78 in abort () from /lib64/libc.so.6
#2  0x00007f372f066a95 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00007f372f064a06 in ?? () from /lib64/libstdc++.so.6
#4  0x00007f372f064a33 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x00007f372f064c53 in __cxa_throw () from /lib64/libstdc++.so.6
#6  0x00007f372b6e23ac in xma_core::utils::check_all_execbo(XmaSession) [clone .cold] () from /opt/xilinx/xrt/lib/libxma2api.so.2
#7  0x00007f372b6f04b0 in xma_thread2(unsigned int) () from /opt/xilinx/xrt/lib/libxma2api.so.2
#8  0x00007f372b707254 in execute_native_thread_routine () from /opt/xilinx/xrt/lib/libxma2api.so.2
#9  0x00007f372e8d9ea5 in start_thread () from /lib64/libpthread.so.0
#10 0x00007f372e602b2d in clone () from /lib64/libc.so.6

The following log is printed:
[XMA] ERROR: XilinxEncoderTest xmautils Session id: 1, type: encoder, Unexpected ERT_CMD_STATE. state=SKCRASHED

kern.log is attached.

[kern.log](https://github.com/Xilinx/XRM/files/11092270/kern.log)

**Comment by bttu** [comment]
@ev-zhuravlev if XRMD is killed, there is no way to avoid the conflict of CU reusing: for example, if process 1 is using encoder 0, then xrmd is killed, thus all cu usage data is lost, even later xrmd is coming up again, xrmd don't know encoder 0 is in use, so xrmd will let process 2 use encoder 0 again.

**Comment by ev-zhuravlev** [comment]
So if xrmd crashes due to crash it is expected that there would be problems with xilinx usage and it's better to restart machine, correct?
But if that case is it possible to fix crash in libxma2api in that scenario so encoder creation would report an error instead of crashing user application?
Thank you

**Comment by bttu** [comment]
It looks two questions here:
1) If xrmd crashed, to stop all the applications using XRM, then restart the xrmd and load xclbin will recover and make the system ready for use, to restart the machine will work for sure, but not required.

2) if one application crash in libxma2api (This is XRT XMA library, not XRM) : it's better to check the reason of the crash, agreed that reporting an error is better than crashing the application.
